--------------------------------------------------------
--  已建立檔案 - 星期三-二月-07-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACTIVITY
--------------------------------------------------------

  CREATE TABLE "MYTODO"."ACTIVITY" 
   (	"ACTIVITY_ID" NUMBER, 
	"ACTIVITY_CAT_ID" NUMBER, 
	"ACTIVITY_NAME" NVARCHAR2(250), 
	"DATE_FROM" DATE, 
	"DATE_TO" DATE, 
	"ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"QUERY_DEF" CLOB, 
	"DB_SCOPE" NVARCHAR2(60), 
	"CREATED_TIME" DATE, 
	"UPDATED_TIME" DATE, 
	"OWNER" NVARCHAR2(30), 
	"MODIFIER" NVARCHAR2(30), 
	"DAYS_OF_BUG" NUMBER(*,0), 
	"DAYS_OF_OTHERS" NUMBER(*,0), 
	"ADDITIONAL_MAIL_TO" CLOB, 
	"ADDITIONAL_MAIL_CC" CLOB, 
	"MAIL_TO_ASSIGNEE" NUMBER, 
	"MAIL_TO_MANAGER" NUMBER, 
	"MAIL_TRIGGER_TIME" CLOB, 
	"ADDITIONAL_MAIL_FIELDS" CLOB, 
	"USER_DEFINED_FIELDS1" CLOB, 
	"USER_DEFINED_FIELDS2" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" 
 LOB ("QUERY_DEF") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("ADDITIONAL_MAIL_TO") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("ADDITIONAL_MAIL_CC") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("MAIL_TRIGGER_TIME") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("ADDITIONAL_MAIL_FIELDS") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("USER_DEFINED_FIELDS1") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("USER_DEFINED_FIELDS2") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 

   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."ACTIVITY_ID" IS 'Use Oracle Sequence : Seq_Activity_ID after insert trigger; Activity_Name + DB_Scope 為 unique';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."ACTIVITY_CAT_ID" IS 'Display as Activity Category Name';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."ACTIVE" IS '0=No, 1=Yes';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."QUERY_DEF" IS '包含該 activity 的 query criteria, sql statement';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."OWNER" IS 'same as ''Users'' Key';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."DAYS_OF_BUG" IS '超過此值該筆 Bug CR highlight 顏色';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."DAYS_OF_OTHERS" IS '超過此值該筆 Others CR highlight 顏色';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."ADDITIONAL_MAIL_TO" IS 'Additional mail list 記錄 Users table ID, 值為多筆 未設置任何 value 時, default 寄給 activity owner';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."ADDITIONAL_MAIL_CC" IS 'Additional mail list 記錄 Users table ID, 值為多筆';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."MAIL_TO_ASSIGNEE" IS 'mail 是否發給每筆 CR assignee, boolean 0 = FALSE, 1 = TRUE';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."MAIL_TO_MANAGER" IS 'mail 是否發給每筆 CR assignee 主管, boolean 0 = FALSE, 1 = TRUE';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."MAIL_TRIGGER_TIME" IS '選擇時間的 UI component 或分成2個欄位存放 Hour / min 使用24小時制 空值未填表示由UI trigger 發送mail';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY"."ADDITIONAL_MAIL_FIELDS" IS '於頁面上固定列出選項, 有勾選時則要在 mail content 中呈現該選項包含的欄位 儲存方式為json format: {""Time"":""0"", ""Remark"":""0"", ""Analysis"":""0"", ""Tracking"":""0"", ""Comments"":""0"" }';
--------------------------------------------------------
--  DDL for Table ACTIVITY_CATEGORY
--------------------------------------------------------

  CREATE TABLE "MYTODO"."ACTIVITY_CATEGORY" 
   (	"ACTIVITY_CAT_ID" NUMBER, 
	"ACTIVITY_CAT_NAME" NVARCHAR2(50), 
	"ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"RELATION_TABLE" CLOB, 
	"DEFAULT_ACTIVITY" NUMBER, 
	"OWNER" NVARCHAR2(30), 
	"CREATED_TIME" DATE, 
	"UPDATED_TIME" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" 
 LOB ("RELATION_TABLE") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 

   COMMENT ON COLUMN "MYTODO"."ACTIVITY_CATEGORY"."ACTIVITY_CAT_ID" IS 'Use Oracle Sequence : Seq_Activity_ID after insert trigger';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY_CATEGORY"."ACTIVE" IS '0=No, 1=Yes';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY_CATEGORY"."RELATION_TABLE" IS 'Multi group at same CLOB field or Defiane relation table';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY_CATEGORY"."DEFAULT_ACTIVITY" IS 'Save Activity_ID in this field Display as Actvitiy Name';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY_CATEGORY"."OWNER" IS 'same as ''Users'' Key';
--------------------------------------------------------
--  DDL for Table ACTIVITY_CR
--------------------------------------------------------

  CREATE TABLE "MYTODO"."ACTIVITY_CR" 
   (	"ACTIVITY_ID" NUMBER, 
	"CR_ID" NVARCHAR2(13), 
	"SYNC_JOB_ID" NVARCHAR2(32), 
	"CREATED_TIME" DATE, 
	"ID" NVARCHAR2(256), 
	"UPDATED_TIME" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
 

   COMMENT ON COLUMN "MYTODO"."ACTIVITY_CR"."ACTIVITY_ID" IS 'Use Oracle Sequence : Seq_Activity_ID after insert trigger';
 
   COMMENT ON COLUMN "MYTODO"."ACTIVITY_CR"."CREATED_TIME" IS '1st created time';
--------------------------------------------------------
--  DDL for Table ACTIVITY_UPDATE_STATUS
--------------------------------------------------------

  CREATE TABLE "MYTODO"."ACTIVITY_UPDATE_STATUS" 
   (	"ID" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"ERROR_CODE" NUMBER, 
	"ERROR_MSG" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table AUTH_GROUP
--------------------------------------------------------

  CREATE TABLE "MYTODO"."AUTH_GROUP" 
   (	"ID" NUMBER(11,0), 
	"NAME" NVARCHAR2(80)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table AUTH_GROUP_PERMISSIONS
--------------------------------------------------------

  CREATE TABLE "MYTODO"."AUTH_GROUP_PERMISSIONS" 
   (	"ID" NUMBER(11,0), 
	"GROUP_ID" NUMBER(11,0), 
	"PERMISSION_ID" NUMBER(11,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table AUTH_PERMISSION
--------------------------------------------------------

  CREATE TABLE "MYTODO"."AUTH_PERMISSION" 
   (	"ID" NUMBER(11,0), 
	"NAME" NVARCHAR2(255), 
	"CONTENT_TYPE_ID" NUMBER(11,0), 
	"CODENAME" NVARCHAR2(100)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table AUTH_USER
--------------------------------------------------------

  CREATE TABLE "MYTODO"."AUTH_USER" 
   (	"ID" NUMBER(11,0), 
	"PASSWORD" NVARCHAR2(128), 
	"LAST_LOGIN" TIMESTAMP (6), 
	"IS_SUPERUSER" NUMBER(1,0), 
	"USERNAME" NVARCHAR2(150), 
	"FIRST_NAME" NVARCHAR2(30), 
	"LAST_NAME" NVARCHAR2(30), 
	"EMAIL" NVARCHAR2(254), 
	"IS_STAFF" NUMBER(1,0), 
	"IS_ACTIVE" NUMBER(1,0), 
	"DATE_JOINED" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table AUTH_USER_GROUPS
--------------------------------------------------------

  CREATE TABLE "MYTODO"."AUTH_USER_GROUPS" 
   (	"ID" NUMBER(11,0), 
	"USER_ID" NUMBER(11,0), 
	"GROUP_ID" NUMBER(11,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table AUTH_USER_USER_PERMISSIONS
--------------------------------------------------------

  CREATE TABLE "MYTODO"."AUTH_USER_USER_PERMISSIONS" 
   (	"ID" NUMBER(11,0), 
	"USER_ID" NUMBER(11,0), 
	"PERMISSION_ID" NUMBER(11,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table CES_SPECIFIC
--------------------------------------------------------

  CREATE TABLE "MYTODO"."CES_SPECIFIC" 
   (	"ID" NVARCHAR2(256), 
	"ACTIVITY_ID" NUMBER, 
	"SYNC_JOB_ID" NVARCHAR2(32), 
	"COUNTRY" NVARCHAR2(50), 
	"OPERATOR" NVARCHAR2(100), 
	"PRIORITY" NVARCHAR2(30), 
	"CR_COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table CR
--------------------------------------------------------

  CREATE TABLE "MYTODO"."CR" 
   (	"CR_ID" NVARCHAR2(13), 
	"TITLE" NVARCHAR2(254), 
	"PRIORITY" NVARCHAR2(30), 
	"CR_CLASS" NVARCHAR2(50), 
	"STATE" NVARCHAR2(254), 
	"CR_SOURCE" NVARCHAR2(50), 
	"BU_TYPE" NVARCHAR2(10), 
	"SUBMITTER" NVARCHAR2(254), 
	"SUBMIT_DATE" DATE, 
	"ASSIGNEE" NVARCHAR2(254), 
	"ASSIGNEE_DEPT" NVARCHAR2(100), 
	"DISPATCH_COUNT" NUMBER, 
	"ASSIGN_DATE" DATE, 
	"RESOLVE_DATE" DATE, 
	"RESOLVE_TIME" NUMBER, 
	"RESOLUTION" NVARCHAR2(30), 
	"CUSTOMER_COMPANY" NVARCHAR2(50), 
	"SOLUTION" CLOB, 
	"INNER_SOLUTION" CLOB, 
	"SOLUTION_CATEGORY_LEVEL1" NVARCHAR2(128), 
	"SOLUTION_CATEGORY_LEVEL2" NVARCHAR2(128), 
	"PLATFORM_GROUP" NVARCHAR2(80), 
	"PATCH_ID" NVARCHAR2(100), 
	"SV_MCE_EFFORT" NVARCHAR2(50), 
	"PLMN1" NVARCHAR2(100), 
	"PLMN2" NVARCHAR2(100), 
	"COUNTRY" NVARCHAR2(50), 
	"COUNTRYCODE" NVARCHAR2(20), 
	"OPERATOR" NVARCHAR2(100), 
	"MD_INFO_COUNTRY" NVARCHAR2(50), 
	"MD_INFO_OP_NAME" NVARCHAR2(100), 
	"RAT1" NVARCHAR2(100), 
	"RAT2" NVARCHAR2(100), 
	"CELL_ID" NVARCHAR2(100), 
	"TAC_LAC" NVARCHAR2(100), 
	"HW_PROJECT_ID" NVARCHAR2(18), 
	"CREATED_TIME" DATE, 
	"UPDATED_TIME" DATE, 
	"IS_ACTIVE" NVARCHAR2(1), 
	"BUG_REASON" NVARCHAR2(128), 
	"LOCAL_ISSUE" NVARCHAR2(300), 
	"TEST_CATEGORY" NVARCHAR2(300)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" 
 LOB ("SOLUTION") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("INNER_SOLUTION") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CR_REVIEWCOMMENTS
--------------------------------------------------------

  CREATE TABLE "MYTODO"."CR_REVIEWCOMMENTS" 
   (	"ID" NUMBER, 
	"CR_ID" NVARCHAR2(13), 
	"ACTIVITY_ID" NUMBER, 
	"LOGIN_NAME" NVARCHAR2(30), 
	"UPDATE_TIME" DATE, 
	"REVIEW_COMMENTS" CLOB, 
	"IS_SYNCED" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" 
 LOB ("REVIEW_COMMENTS") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 

   COMMENT ON COLUMN "MYTODO"."CR_REVIEWCOMMENTS"."ID" IS '自動產生之流水號';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWCOMMENTS"."CR_ID" IS 'CR ID + Activity ID 可串到 CR_ReviewInfo';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWCOMMENTS"."ACTIVITY_ID" IS 'CR ID + Activity ID 可串到 CR_ReviewInfo';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWCOMMENTS"."LOGIN_NAME" IS '工號 (Users.Login_Name)';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWCOMMENTS"."UPDATE_TIME" IS 'last update time';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWCOMMENTS"."IS_SYNCED" IS '當CR_ReviewInfo = 1, 找出相同 CR ID & Is_Synced = 0 之 data, sync 完成後標示為 1';
--------------------------------------------------------
--  DDL for Table CR_REVIEWINFO
--------------------------------------------------------

  CREATE TABLE "MYTODO"."CR_REVIEWINFO" 
   (	"CR_ID" NVARCHAR2(13), 
	"UPDATED_TIME" DATE, 
	"SYNC_TO_WITS" NUMBER(1,0), 
	"WAIVED" NVARCHAR2(2), 
	"ACTIVITY_ID" NUMBER, 
	"IMPORTANCE" NVARCHAR2(40), 
	"WAR_ROOM" NVARCHAR2(60), 
	"PROGRESS" NVARCHAR2(80), 
	"REMARK" CLOB, 
	"REVIEWED" NUMBER, 
	"ID" NVARCHAR2(100), 
	"ADDITIONAL_FIELDS" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" 
 LOB ("REMARK") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("ADDITIONAL_FIELDS") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 

   COMMENT ON COLUMN "MYTODO"."CR_REVIEWINFO"."UPDATED_TIME" IS 'fileds 有異動時記錄update時間';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWINFO"."SYNC_TO_WITS" IS '1=Sync Comments  to CR note
Checkbox on UI';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWINFO"."IMPORTANCE" IS 'Filter "Tracking" 有勾選時才顯示';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWINFO"."WAR_ROOM" IS 'Filter "Tracking" 有勾選時才顯示';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWINFO"."PROGRESS" IS 'Filter "Tracking" 有勾選時才顯示';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWINFO"."REMARK" IS 'Filter "Remark" 有勾選時才顯示';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWINFO"."REVIEWED" IS '是否已完成 CR review; 0 = FALSE, 1 = TRUE';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWINFO"."ID" IS 'CR_ID + "_" + ACTIVITY_ID';
 
   COMMENT ON COLUMN "MYTODO"."CR_REVIEWINFO"."ADDITIONAL_FIELDS" IS '允許多個欄位, 格式為 json format: {"field1" : "value1", "field2" : "value1", "field3" : "value3", "field4" : "value4", ....... }  前端對此一欄位特別處理, 每一 field:value 將會顯示於 data table中';
--------------------------------------------------------
--  DDL for Table CRM_HW_PROJECT
--------------------------------------------------------

  CREATE TABLE "MYTODO"."CRM_HW_PROJECT" 
   (	"HW_PROJECT_ID" NVARCHAR2(18), 
	"HW_TYPE" NVARCHAR2(50), 
	"HW_PROJECT_STATUS" NVARCHAR2(50), 
	"HW_PROJECT_NAME" NVARCHAR2(100), 
	"COMPANY" NVARCHAR2(50), 
	"SWPM_FULLNAME" NVARCHAR2(50), 
	"PLATFORM" NVARCHAR2(80), 
	"OPERATOR" NVARCHAR2(100), 
	"FTA" NVARCHAR2(100), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"COMPLETED" NVARCHAR2(1), 
	"IS_ACTIVE" NVARCHAR2(1), 
	"ID" NVARCHAR2(256)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
 

   COMMENT ON COLUMN "MYTODO"."CRM_HW_PROJECT"."ID" IS 'HW_Project_ID + HW_TYPE + Operator (2018/1/22)';
--------------------------------------------------------
--  DDL for Table CRM_HW_PROJECT_MILESTONE
--------------------------------------------------------

  CREATE TABLE "MYTODO"."CRM_HW_PROJECT_MILESTONE" 
   (	"HW_PROJECT_ID" NVARCHAR2(18), 
	"TYPE" NVARCHAR2(100), 
	"MILESTONE_NAME" NVARCHAR2(100), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"WITH_VOTE" NVARCHAR2(1), 
	"WITH_WFC" NVARCHAR2(1), 
	"WITH_VILTE" NVARCHAR2(1), 
	"COMPLETED" NVARCHAR2(1), 
	"IS_ACTIVE" NVARCHAR2(1), 
	"ID" NVARCHAR2(256), 
	"OPERATOR" NVARCHAR2(100), 
	"MILESTONE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
 

   COMMENT ON COLUMN "MYTODO"."CRM_HW_PROJECT_MILESTONE"."ID" IS 'HW_Project_ID + TYPE+MILESTONE_NAME+Operator (2018/1/22)';
--------------------------------------------------------
--  DDL for Table DEPTS
--------------------------------------------------------

  CREATE TABLE "MYTODO"."DEPTS" 
   (	"DEPT_ID" NUMBER(10,0), 
	"DEPT_NAME" NVARCHAR2(30), 
	"IS_ACTIVE" NUMBER(1,0), 
	"CREATED_TIME" DATE, 
	"UPDATED_TIME" DATE, 
	"SITE" NVARCHAR2(10), 
	"DEPT_MANGR" NVARCHAR2(30), 
	"PARENT_DEPT" NVARCHAR2(10)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
 

   COMMENT ON COLUMN "MYTODO"."DEPTS"."DEPT_ID" IS 'groups.dbid';
 
   COMMENT ON COLUMN "MYTODO"."DEPTS"."DEPT_NAME" IS 'groups.name';
 
   COMMENT ON COLUMN "MYTODO"."DEPTS"."IS_ACTIVE" IS 'groups.is_active , 0=inactive, 1=active';
 
   COMMENT ON COLUMN "MYTODO"."DEPTS"."CREATED_TIME" IS '1st created time';
 
   COMMENT ON COLUMN "MYTODO"."DEPTS"."UPDATED_TIME" IS 'Last updated time';
--------------------------------------------------------
--  DDL for Table DJANGO_ADMIN_LOG
--------------------------------------------------------

  CREATE TABLE "MYTODO"."DJANGO_ADMIN_LOG" 
   (	"ID" NUMBER(11,0), 
	"ACTION_TIME" TIMESTAMP (6) DEFAULT NULL, 
	"OBJECT_ID" NCLOB, 
	"OBJECT_REPR" NVARCHAR2(200), 
	"ACTION_FLAG" NUMBER(11,0), 
	"CHANGE_MESSAGE" NCLOB, 
	"CONTENT_TYPE_ID" NUMBER(11,0), 
	"USER_ID" NUMBER(11,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" 
 LOB ("OBJECT_ID") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("CHANGE_MESSAGE") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DJANGO_CONTENT_TYPE
--------------------------------------------------------

  CREATE TABLE "MYTODO"."DJANGO_CONTENT_TYPE" 
   (	"ID" NUMBER(11,0), 
	"APP_LABEL" NVARCHAR2(100), 
	"MODEL" NVARCHAR2(100)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table DJANGO_MIGRATIONS
--------------------------------------------------------

  CREATE TABLE "MYTODO"."DJANGO_MIGRATIONS" 
   (	"ID" NUMBER(11,0), 
	"APP" NVARCHAR2(255), 
	"NAME" NVARCHAR2(255), 
	"APPLIED" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table DJANGO_SESSION
--------------------------------------------------------

  CREATE TABLE "MYTODO"."DJANGO_SESSION" 
   (	"SESSION_KEY" NVARCHAR2(40), 
	"SESSION_DATA" NCLOB, 
	"EXPIRE_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" 
 LOB ("SESSION_DATA") STORE AS (
  TABLESPACE "MYTODO" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FTA
--------------------------------------------------------

  CREATE TABLE "MYTODO"."FTA" 
   (	"ID" NVARCHAR2(256), 
	"ACTIVITY_ID" NUMBER, 
	"SYNC_JOB_ID" NVARCHAR2(32), 
	"OPERATOR" NVARCHAR2(100), 
	"AREA" NVARCHAR2(50), 
	"IS_COMPLETED" NVARCHAR2(1), 
	"PLATFORM" NVARCHAR2(80), 
	"COMPANY" NVARCHAR2(50), 
	"PERIOD_YEAR" NVARCHAR2(4), 
	"PERIOD_WEEK" NVARCHAR2(6), 
	"PROJECT_COUNT" NUMBER, 
	"WILL_KICKOFF_PROJECT_COUNT" NUMBER, 
	"URGENT_CR_COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table MD_MCC_MNC
--------------------------------------------------------

  CREATE TABLE "MYTODO"."MD_MCC_MNC" 
   (	"MCC" NVARCHAR2(3), 
	"MCN" NVARCHAR2(3), 
	"AREA" NVARCHAR2(20), 
	"COUNTRY" NVARCHAR2(100), 
	"COUNTRY_CODE" NVARCHAR2(20), 
	"OPERATOR" NVARCHAR2(100), 
	"CREATED_TIME" DATE, 
	"UPDATED_TIME" DATE, 
	"ID" NVARCHAR2(256)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table MYTODO_ACCESSLOG
--------------------------------------------------------

  CREATE TABLE "MYTODO"."MYTODO_ACCESSLOG" 
   (	"FROM_ADDR" VARCHAR2(25 BYTE), 
	"DBID" NUMBER(10,0), 
	"REPOSITORY" VARCHAR2(100 BYTE), 
	"USERDB" VARCHAR2(100 BYTE), 
	"CREATED_AT" DATE, 
	"ELAPSE_TIME" NUMBER, 
	"QUERY_TYPE" VARCHAR2(20 BYTE), 
	"SESSION_ID" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PARAM" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table MYTODO_RUNATSTART
--------------------------------------------------------

  CREATE TABLE "MYTODO"."MYTODO_RUNATSTART" 
   (	"USERNAME" VARCHAR2(50 BYTE), 
	"STARTQUERY" VARCHAR2(20 BYTE), 
	"CLANDB" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table OP_AREA
--------------------------------------------------------

  CREATE TABLE "MYTODO"."OP_AREA" 
   (	"AREA" NVARCHAR2(20), 
	"OPERATOR" NVARCHAR2(100)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table OP_GROUP
--------------------------------------------------------

  CREATE TABLE "MYTODO"."OP_GROUP" 
   (	"GROUP_NAME" NVARCHAR2(50), 
	"TYPE" NVARCHAR2(50), 
	"VALUE" NVARCHAR2(100), 
	"ID" NVARCHAR2(256)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table OPEN_ESERVICES
--------------------------------------------------------

  CREATE TABLE "MYTODO"."OPEN_ESERVICES" 
   (	"ID" NVARCHAR2(256), 
	"ACTIVITY_ID" NUMBER, 
	"SYNC_JOB_ID" NVARCHAR2(32), 
	"ASSIGNEE_SITE" NVARCHAR2(50), 
	"CUSTOMER_COMPANY" NVARCHAR2(50), 
	"STAY_SUBMITTED" NVARCHAR2(20), 
	"PRIORITY" NVARCHAR2(30), 
	"CR_COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table OPERATOR_CERTIFICATION
--------------------------------------------------------

  CREATE TABLE "MYTODO"."OPERATOR_CERTIFICATION" 
   (	"ID" NVARCHAR2(256), 
	"ACTIVITY_ID" NUMBER, 
	"SYNC_JOB_ID" NVARCHAR2(32), 
	"OPERATOR" NVARCHAR2(100), 
	"AREA" NVARCHAR2(50), 
	"IS_COMPLETED" NVARCHAR2(1), 
	"PLATFORM" NVARCHAR2(80), 
	"COMPANY" NVARCHAR2(50), 
	"PERIOD_YEAR" NVARCHAR2(4), 
	"PERIOD_WEEK" NVARCHAR2(6), 
	"PROJECT_COUNT" NUMBER, 
	"WILL_KICKOFF_PROJECT_COUNT" NUMBER, 
	"URGENT_CR_COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table RESOLVED_ESERIVES
--------------------------------------------------------

  CREATE TABLE "MYTODO"."RESOLVED_ESERIVES" 
   (	"ID" NVARCHAR2(256), 
	"ACTIVITY_ID" NUMBER, 
	"SYNC_JOB_ID" NVARCHAR2(32), 
	"TYPE" NVARCHAR2(10), 
	"ASSIGNEE_SITE" NVARCHAR2(50), 
	"CUSTOMER_COMPANY" NVARCHAR2(50), 
	"PERIOD" NVARCHAR2(8), 
	"PRIORITY" NVARCHAR2(30), 
	"CR_COUNT" NUMBER, 
	"RESOLVE_TIME_COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table SYNC_CONTROL
--------------------------------------------------------

  CREATE TABLE "MYTODO"."SYNC_CONTROL" 
   (	"ID" NVARCHAR2(100), 
	"SYNC_NAME" NVARCHAR2(100), 
	"SYNC_TYPE" NVARCHAR2(10), 
	"SYNC_VALUE" NVARCHAR2(100), 
	"SYNC_LASTDATE" DATE, 
	"SYNC_SYSTEM" NVARCHAR2(100), 
	"SYNC_SOURCE" NVARCHAR2(100), 
	"SYNC_SCRIPT_INFO" NVARCHAR2(200)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table SYNC_JOB
--------------------------------------------------------

  CREATE TABLE "MYTODO"."SYNC_JOB" 
   (	"ACTIVITY_ID" NUMBER, 
	"SYNC_JOB_ID" NVARCHAR2(32), 
	"CREATED_TIME" DATE, 
	"IS_ACTIVE" NVARCHAR2(1)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "MYTODO"."TEST" 
   (	"ID" VARCHAR2(1 BYTE), 
	"NAME" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "MYTODO"."USERS" 
   (	"DEPT_ID" NUMBER(10,0), 
	"LOGIN_NAME" NVARCHAR2(30), 
	"FULL_NAME" NVARCHAR2(50), 
	"E_MAIL" NVARCHAR2(100), 
	"IS_ACTIVE" NUMBER(1,0), 
	"IS_ADMIN" NUMBER(1,0), 
	"IS_SUPPERUSER" NUMBER(1,0), 
	"CREATED_TIME" DATE, 
	"UPDATED_TIME" DATE, 
	"DEPT_NAME" NVARCHAR2(60), 
	"SITE" NVARCHAR2(10), 
	"REPORTING_MANAGER" NVARCHAR2(30)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
 

   COMMENT ON COLUMN "MYTODO"."USERS"."DEPT_ID" IS 'users.groups';
 
   COMMENT ON COLUMN "MYTODO"."USERS"."LOGIN_NAME" IS 'users.login_name';
 
   COMMENT ON COLUMN "MYTODO"."USERS"."FULL_NAME" IS 'users.fullname';
 
   COMMENT ON COLUMN "MYTODO"."USERS"."E_MAIL" IS 'users.email';
 
   COMMENT ON COLUMN "MYTODO"."USERS"."IS_ACTIVE" IS 'users.is_active , 0=inactive, 1=active
';
 
   COMMENT ON COLUMN "MYTODO"."USERS"."IS_ADMIN" IS '1=admin
';
 
   COMMENT ON COLUMN "MYTODO"."USERS"."IS_SUPPERUSER" IS '1=supper user
';
 
   COMMENT ON COLUMN "MYTODO"."USERS"."CREATED_TIME" IS '1st created time
';
 
   COMMENT ON COLUMN "MYTODO"."USERS"."UPDATED_TIME" IS 'Last updated time
';
--------------------------------------------------------
--  DDL for Table WWSTATISTICMAP
--------------------------------------------------------

  CREATE TABLE "MYTODO"."WWSTATISTICMAP" 
   (	"ID" NVARCHAR2(256), 
	"ACTIVITY_ID" NUMBER, 
	"SYNC_JOB_ID" NVARCHAR2(32), 
	"STATE" NVARCHAR2(32), 
	"PERIOD" NVARCHAR2(4), 
	"COUNTRY" NVARCHAR2(50), 
	"OPERATOR" NVARCHAR2(100), 
	"MD_CLASS" NVARCHAR2(50), 
	"CR_COUNT" NUMBER, 
	"URGENT_CR_COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Table WWSTATISTICTOP10
--------------------------------------------------------

  CREATE TABLE "MYTODO"."WWSTATISTICTOP10" 
   (	"ID" NVARCHAR2(256), 
	"ACTIVITY_ID" NUMBER, 
	"SYNC_JOB_ID" NVARCHAR2(32), 
	"PERIOD" NVARCHAR2(4), 
	"TYPE" NVARCHAR2(10), 
	"TYPE_VALUE" NVARCHAR2(100), 
	"PRIORITY" NVARCHAR2(30), 
	"CR_COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index ACTIVITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."ACTIVITY_PK" ON "MYTODO"."ACTIVITY" ("ACTIVITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index ACTIVITYCATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."ACTIVITYCATEGORY_PK" ON "MYTODO"."ACTIVITY_CATEGORY" ("ACTIVITY_CAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080102
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080102" ON "MYTODO"."ACTIVITY_CR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index ACTIVITY_UPDATE_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."ACTIVITY_UPDATE_STATUS_PK" ON "MYTODO"."ACTIVITY_UPDATE_STATUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080110
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080110" ON "MYTODO"."AUTH_GROUP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080111
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080111" ON "MYTODO"."AUTH_GROUP" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index AUTH_GROU_GROUP_ID__0CD325B0_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."AUTH_GROU_GROUP_ID__0CD325B0_U" ON "MYTODO"."AUTH_GROUP_PERMISSIONS" ("GROUP_ID", "PERMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index AUTH_GROUP_GROUP_ID_B120CBF9
--------------------------------------------------------

  CREATE INDEX "MYTODO"."AUTH_GROUP_GROUP_ID_B120CBF9" ON "MYTODO"."AUTH_GROUP_PERMISSIONS" ("GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index AUTH_GROUP_PERMISSION_84C5C92E
--------------------------------------------------------

  CREATE INDEX "MYTODO"."AUTH_GROUP_PERMISSION_84C5C92E" ON "MYTODO"."AUTH_GROUP_PERMISSIONS" ("PERMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080112
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080112" ON "MYTODO"."AUTH_GROUP_PERMISSIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index AUTH_PERM_CONTENT_T_01AB375A_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."AUTH_PERM_CONTENT_T_01AB375A_U" ON "MYTODO"."AUTH_PERMISSION" ("CONTENT_TYPE_ID", "CODENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index AUTH_PERMI_CONTENT_TY_2F476E4B
--------------------------------------------------------

  CREATE INDEX "MYTODO"."AUTH_PERMI_CONTENT_TY_2F476E4B" ON "MYTODO"."AUTH_PERMISSION" ("CONTENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080108
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080108" ON "MYTODO"."AUTH_PERMISSION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080117
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080117" ON "MYTODO"."AUTH_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080118
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080118" ON "MYTODO"."AUTH_USER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER_USER_ID_G_94350C0C_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."AUTH_USER_USER_ID_G_94350C0C_U" ON "MYTODO"."AUTH_USER_GROUPS" ("USER_ID", "GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER__USER_ID_6A12ED8B
--------------------------------------------------------

  CREATE INDEX "MYTODO"."AUTH_USER__USER_ID_6A12ED8B" ON "MYTODO"."AUTH_USER_GROUPS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER__GROUP_ID_97559544
--------------------------------------------------------

  CREATE INDEX "MYTODO"."AUTH_USER__GROUP_ID_97559544" ON "MYTODO"."AUTH_USER_GROUPS" ("GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080119
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080119" ON "MYTODO"."AUTH_USER_GROUPS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER_USER_ID_P_14A6B632_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."AUTH_USER_USER_ID_P_14A6B632_U" ON "MYTODO"."AUTH_USER_USER_PERMISSIONS" ("USER_ID", "PERMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER__USER_ID_A95EAD1B
--------------------------------------------------------

  CREATE INDEX "MYTODO"."AUTH_USER__USER_ID_A95EAD1B" ON "MYTODO"."AUTH_USER_USER_PERMISSIONS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER__PERMISSION_1FBB5F2C
--------------------------------------------------------

  CREATE INDEX "MYTODO"."AUTH_USER__PERMISSION_1FBB5F2C" ON "MYTODO"."AUTH_USER_USER_PERMISSIONS" ("PERMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080121
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080121" ON "MYTODO"."AUTH_USER_USER_PERMISSIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080133
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080133" ON "MYTODO"."CES_SPECIFIC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080134
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080134" ON "MYTODO"."CR" ("CR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index CR_REVIEWCOMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."CR_REVIEWCOMMENTS_PK" ON "MYTODO"."CR_REVIEWCOMMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index CR_REVIEWINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."CR_REVIEWINFO_PK" ON "MYTODO"."CR_REVIEWINFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080132
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080132" ON "MYTODO"."CRM_HW_PROJECT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080139
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080139" ON "MYTODO"."CRM_HW_PROJECT_MILESTONE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index DEPTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."DEPTS_PK" ON "MYTODO"."DEPTS" ("DEPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index DJANGO_ADM_CONTENT_TY_C4BCE8EB
--------------------------------------------------------

  CREATE INDEX "MYTODO"."DJANGO_ADM_CONTENT_TY_C4BCE8EB" ON "MYTODO"."DJANGO_ADMIN_LOG" ("CONTENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index DJANGO_ADM_USER_ID_C564EBA6
--------------------------------------------------------

  CREATE INDEX "MYTODO"."DJANGO_ADM_USER_ID_C564EBA6" ON "MYTODO"."DJANGO_ADMIN_LOG" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080124
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080124" ON "MYTODO"."DJANGO_ADMIN_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index DJANGO_CO_APP_LABEL_76BD3D3B_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."DJANGO_CO_APP_LABEL_76BD3D3B_U" ON "MYTODO"."DJANGO_CONTENT_TYPE" ("APP_LABEL", "MODEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080106
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080106" ON "MYTODO"."DJANGO_CONTENT_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080105
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080105" ON "MYTODO"."DJANGO_MIGRATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index DJANGO_SES_EXPIRE_DAT_A5C62663
--------------------------------------------------------

  CREATE INDEX "MYTODO"."DJANGO_SES_EXPIRE_DAT_A5C62663" ON "MYTODO"."DJANGO_SESSION" ("EXPIRE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080125
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080125" ON "MYTODO"."DJANGO_SESSION" ("SESSION_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080137
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080137" ON "MYTODO"."FTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080130
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080130" ON "MYTODO"."MD_MCC_MNC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index MYTODO_ACCESSLOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."MYTODO_ACCESSLOG_PK" ON "MYTODO"."MYTODO_ACCESSLOG" ("DBID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index MYTODO_RUNATSTART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."MYTODO_RUNATSTART_PK" ON "MYTODO"."MYTODO_RUNATSTART" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080131
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080131" ON "MYTODO"."OP_AREA" ("OPERATOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080138
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080138" ON "MYTODO"."OP_GROUP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080135
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080135" ON "MYTODO"."OPEN_ESERVICES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080136
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080136" ON "MYTODO"."OPERATOR_CERTIFICATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080129
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080129" ON "MYTODO"."RESOLVED_ESERIVES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080140
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080140" ON "MYTODO"."SYNC_CONTROL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080126
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080126" ON "MYTODO"."SYNC_JOB" ("SYNC_JOB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080098
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080098" ON "MYTODO"."TEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080100
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080100" ON "MYTODO"."USERS" ("LOGIN_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080128
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080128" ON "MYTODO"."WWSTATISTICMAP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0080127
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYTODO"."SYS_C0080127" ON "MYTODO"."WWSTATISTICTOP10" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO" ;
--------------------------------------------------------
--  DDL for Trigger ACTIVITY_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."ACTIVITY_TR" 
BEFORE INSERT ON ACTIVITY
FOR EACH ROW
  WHEN (new."ACTIVITY_ID" IS NULL) BEGIN
    SELECT "SEQ_ACTIVITY_ID".nextval
        INTO :new."ACTIVITY_ID" FROM dual;   
END;

/
ALTER TRIGGER "MYTODO"."ACTIVITY_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACTIVITY_CATEGORY_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."ACTIVITY_CATEGORY_TR" 
BEFORE INSERT ON ACTIVITY_CATEGORY
FOR EACH ROW
  WHEN (new."ACTIVITY_CAT_ID" IS NULL) BEGIN
    SELECT "SEQ_ACTIVITY_CAT_ID".nextval
        INTO :new."ACTIVITY_CAT_ID" FROM dual;   
END;

/
ALTER TRIGGER "MYTODO"."ACTIVITY_CATEGORY_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTH_GROUP_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."AUTH_GROUP_TR" 
BEFORE INSERT ON "AUTH_GROUP"
FOR EACH ROW
  WHEN (new."ID" IS NULL) BEGIN
        SELECT "AUTH_GROUP_SQ".nextval
        INTO :new."ID" FROM dual;
    END;


/
ALTER TRIGGER "MYTODO"."AUTH_GROUP_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTH_GROUP_PERMISSIONS_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."AUTH_GROUP_PERMISSIONS_TR" 
BEFORE INSERT ON "AUTH_GROUP_PERMISSIONS"
FOR EACH ROW
  WHEN (new."ID" IS NULL) BEGIN
        SELECT "AUTH_GROUP_PERMISSIONS_SQ".nextval
        INTO :new."ID" FROM dual;
    END;


/
ALTER TRIGGER "MYTODO"."AUTH_GROUP_PERMISSIONS_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTH_PERMISSION_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."AUTH_PERMISSION_TR" 
BEFORE INSERT ON "AUTH_PERMISSION"
FOR EACH ROW
  WHEN (new."ID" IS NULL) BEGIN
        SELECT "AUTH_PERMISSION_SQ".nextval
        INTO :new."ID" FROM dual;
    END;


/
ALTER TRIGGER "MYTODO"."AUTH_PERMISSION_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTH_USER_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."AUTH_USER_TR" 
BEFORE INSERT ON "AUTH_USER"
FOR EACH ROW
  WHEN (new."ID" IS NULL) BEGIN
        SELECT "AUTH_USER_SQ".nextval
        INTO :new."ID" FROM dual;
    END;


/
ALTER TRIGGER "MYTODO"."AUTH_USER_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTH_USER_GROUPS_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."AUTH_USER_GROUPS_TR" 
BEFORE INSERT ON "AUTH_USER_GROUPS"
FOR EACH ROW
  WHEN (new."ID" IS NULL) BEGIN
        SELECT "AUTH_USER_GROUPS_SQ".nextval
        INTO :new."ID" FROM dual;
    END;


/
ALTER TRIGGER "MYTODO"."AUTH_USER_GROUPS_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTH_USER_USER_PERMISSIONS_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."AUTH_USER_USER_PERMISSIONS_TR" 
BEFORE INSERT ON "AUTH_USER_USER_PERMISSIONS"
FOR EACH ROW
  WHEN (new."ID" IS NULL) BEGIN
        SELECT "AUTH_USER_USER_PERMISSIONS_SQ".nextval
        INTO :new."ID" FROM dual;
    END;


/
ALTER TRIGGER "MYTODO"."AUTH_USER_USER_PERMISSIONS_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CR_REVIEWCOMMENTS_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."CR_REVIEWCOMMENTS_TR" 
BEFORE INSERT ON CR_REVIEWCOMMENTS
FOR EACH ROW
  WHEN (new."ID" IS NULL) BEGIN
    SELECT "SEQ_CR_REVIEWCOMMENTS_ID".nextval
        INTO :new."ID" FROM dual;   
END;

/
ALTER TRIGGER "MYTODO"."CR_REVIEWCOMMENTS_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DJANGO_ADMIN_LOG_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."DJANGO_ADMIN_LOG_TR" 
BEFORE INSERT ON "DJANGO_ADMIN_LOG"
FOR EACH ROW
  WHEN (new."ID" IS NULL) BEGIN
        SELECT "DJANGO_ADMIN_LOG_SQ".nextval
        INTO :new."ID" FROM dual;
    END;


/
ALTER TRIGGER "MYTODO"."DJANGO_ADMIN_LOG_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DJANGO_CONTENT_TYPE_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."DJANGO_CONTENT_TYPE_TR" 
BEFORE INSERT ON "DJANGO_CONTENT_TYPE"
FOR EACH ROW
  WHEN (new."ID" IS NULL) BEGIN
        SELECT "DJANGO_CONTENT_TYPE_SQ".nextval
        INTO :new."ID" FROM dual;
    END;


/
ALTER TRIGGER "MYTODO"."DJANGO_CONTENT_TYPE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DJANGO_MIGRATIONS_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MYTODO"."DJANGO_MIGRATIONS_TR" 
BEFORE INSERT ON "DJANGO_MIGRATIONS"
FOR EACH ROW
  WHEN (new."ID" IS NULL) BEGIN
        SELECT "DJANGO_MIGRATIONS_SQ".nextval
        INTO :new."ID" FROM dual;
    END;


/
ALTER TRIGGER "MYTODO"."DJANGO_MIGRATIONS_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table ACTIVITY
--------------------------------------------------------

  ALTER TABLE "MYTODO"."ACTIVITY" ADD CONSTRAINT "ACTIVITY_PK" PRIMARY KEY ("ACTIVITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."ACTIVITY" MODIFY ("ACTIVITY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACTIVITY_CATEGORY
--------------------------------------------------------

  ALTER TABLE "MYTODO"."ACTIVITY_CATEGORY" ADD CONSTRAINT "ACTIVITYCATEGORY_PK" PRIMARY KEY ("ACTIVITY_CAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."ACTIVITY_CATEGORY" MODIFY ("ACTIVITY_CAT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACTIVITY_CR
--------------------------------------------------------

  ALTER TABLE "MYTODO"."ACTIVITY_CR" MODIFY ("ACTIVITY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."ACTIVITY_CR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACTIVITY_UPDATE_STATUS
--------------------------------------------------------

  ALTER TABLE "MYTODO"."ACTIVITY_UPDATE_STATUS" ADD CONSTRAINT "ACTIVITY_UPDATE_STATUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."ACTIVITY_UPDATE_STATUS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_GROUP
--------------------------------------------------------

  ALTER TABLE "MYTODO"."AUTH_GROUP" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_GROUP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."AUTH_GROUP" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_GROUP_PERMISSIONS
--------------------------------------------------------

  ALTER TABLE "MYTODO"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "AUTH_GROU_GROUP_ID__0CD325B0_U" UNIQUE ("GROUP_ID", "PERMISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."AUTH_GROUP_PERMISSIONS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_GROUP_PERMISSIONS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_GROUP_PERMISSIONS" MODIFY ("PERMISSION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_GROUP_PERMISSIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_PERMISSION
--------------------------------------------------------

  ALTER TABLE "MYTODO"."AUTH_PERMISSION" ADD CONSTRAINT "AUTH_PERM_CONTENT_T_01AB375A_U" UNIQUE ("CONTENT_TYPE_ID", "CODENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."AUTH_PERMISSION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_PERMISSION" MODIFY ("CONTENT_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_PERMISSION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_USER
--------------------------------------------------------

  ALTER TABLE "MYTODO"."AUTH_USER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_USER" MODIFY ("IS_SUPERUSER" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_USER" MODIFY ("IS_STAFF" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_USER" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_USER" MODIFY ("DATE_JOINED" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_USER" ADD CHECK ("IS_SUPERUSER" IN (0,1)) ENABLE;
 
  ALTER TABLE "MYTODO"."AUTH_USER" ADD CHECK ("IS_STAFF" IN (0,1)) ENABLE;
 
  ALTER TABLE "MYTODO"."AUTH_USER" ADD CHECK ("IS_ACTIVE" IN (0,1)) ENABLE;
 
  ALTER TABLE "MYTODO"."AUTH_USER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."AUTH_USER" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_USER_GROUPS
--------------------------------------------------------

  ALTER TABLE "MYTODO"."AUTH_USER_GROUPS" ADD CONSTRAINT "AUTH_USER_USER_ID_G_94350C0C_U" UNIQUE ("USER_ID", "GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."AUTH_USER_GROUPS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_USER_GROUPS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_USER_GROUPS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_USER_GROUPS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_USER_USER_PERMISSIONS
--------------------------------------------------------

  ALTER TABLE "MYTODO"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "AUTH_USER_USER_ID_P_14A6B632_U" UNIQUE ("USER_ID", "PERMISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."AUTH_USER_USER_PERMISSIONS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_USER_USER_PERMISSIONS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_USER_USER_PERMISSIONS" MODIFY ("PERMISSION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."AUTH_USER_USER_PERMISSIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CES_SPECIFIC
--------------------------------------------------------

  ALTER TABLE "MYTODO"."CES_SPECIFIC" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CR
--------------------------------------------------------

  ALTER TABLE "MYTODO"."CR" ADD PRIMARY KEY ("CR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CR_REVIEWCOMMENTS
--------------------------------------------------------

  ALTER TABLE "MYTODO"."CR_REVIEWCOMMENTS" ADD CONSTRAINT "CR_REVIEWCOMMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."CR_REVIEWCOMMENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CR_REVIEWINFO
--------------------------------------------------------

  ALTER TABLE "MYTODO"."CR_REVIEWINFO" ADD CONSTRAINT "CR_REVIEWINFO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."CR_REVIEWINFO" MODIFY ("CR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."CR_REVIEWINFO" MODIFY ("ACTIVITY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."CR_REVIEWINFO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CRM_HW_PROJECT
--------------------------------------------------------

  ALTER TABLE "MYTODO"."CRM_HW_PROJECT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CRM_HW_PROJECT_MILESTONE
--------------------------------------------------------

  ALTER TABLE "MYTODO"."CRM_HW_PROJECT_MILESTONE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPTS
--------------------------------------------------------

  ALTER TABLE "MYTODO"."DEPTS" ADD CONSTRAINT "DEPTS_PK" PRIMARY KEY ("DEPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."DEPTS" MODIFY ("DEPT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DJANGO_ADMIN_LOG
--------------------------------------------------------

  ALTER TABLE "MYTODO"."DJANGO_ADMIN_LOG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."DJANGO_ADMIN_LOG" MODIFY ("ACTION_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."DJANGO_ADMIN_LOG" MODIFY ("ACTION_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."DJANGO_ADMIN_LOG" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."DJANGO_ADMIN_LOG" ADD CHECK ("ACTION_FLAG" >= 0) ENABLE;
 
  ALTER TABLE "MYTODO"."DJANGO_ADMIN_LOG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DJANGO_CONTENT_TYPE
--------------------------------------------------------

  ALTER TABLE "MYTODO"."DJANGO_CONTENT_TYPE" ADD CONSTRAINT "DJANGO_CO_APP_LABEL_76BD3D3B_U" UNIQUE ("APP_LABEL", "MODEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."DJANGO_CONTENT_TYPE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."DJANGO_CONTENT_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DJANGO_MIGRATIONS
--------------------------------------------------------

  ALTER TABLE "MYTODO"."DJANGO_MIGRATIONS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."DJANGO_MIGRATIONS" MODIFY ("APPLIED" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."DJANGO_MIGRATIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DJANGO_SESSION
--------------------------------------------------------

  ALTER TABLE "MYTODO"."DJANGO_SESSION" MODIFY ("SESSION_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."DJANGO_SESSION" MODIFY ("EXPIRE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."DJANGO_SESSION" ADD PRIMARY KEY ("SESSION_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FTA
--------------------------------------------------------

  ALTER TABLE "MYTODO"."FTA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MD_MCC_MNC
--------------------------------------------------------

  ALTER TABLE "MYTODO"."MD_MCC_MNC" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MYTODO_ACCESSLOG
--------------------------------------------------------

  ALTER TABLE "MYTODO"."MYTODO_ACCESSLOG" ADD CONSTRAINT "MYTODO_ACCESSLOG_PK" PRIMARY KEY ("DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."MYTODO_ACCESSLOG" MODIFY ("FROM_ADDR" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."MYTODO_ACCESSLOG" MODIFY ("DBID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."MYTODO_ACCESSLOG" MODIFY ("REPOSITORY" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."MYTODO_ACCESSLOG" MODIFY ("USERDB" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."MYTODO_ACCESSLOG" MODIFY ("CREATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."MYTODO_ACCESSLOG" MODIFY ("ELAPSE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."MYTODO_ACCESSLOG" MODIFY ("QUERY_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."MYTODO_ACCESSLOG" MODIFY ("SESSION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."MYTODO_ACCESSLOG" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MYTODO_RUNATSTART
--------------------------------------------------------

  ALTER TABLE "MYTODO"."MYTODO_RUNATSTART" ADD CONSTRAINT "MYTODO_RUNATSTART_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
 
  ALTER TABLE "MYTODO"."MYTODO_RUNATSTART" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."MYTODO_RUNATSTART" MODIFY ("STARTQUERY" NOT NULL ENABLE);
 
  ALTER TABLE "MYTODO"."MYTODO_RUNATSTART" MODIFY ("CLANDB" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OP_AREA
--------------------------------------------------------

  ALTER TABLE "MYTODO"."OP_AREA" ADD PRIMARY KEY ("OPERATOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OP_GROUP
--------------------------------------------------------

  ALTER TABLE "MYTODO"."OP_GROUP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OPEN_ESERVICES
--------------------------------------------------------

  ALTER TABLE "MYTODO"."OPEN_ESERVICES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OPERATOR_CERTIFICATION
--------------------------------------------------------

  ALTER TABLE "MYTODO"."OPERATOR_CERTIFICATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESOLVED_ESERIVES
--------------------------------------------------------

  ALTER TABLE "MYTODO"."RESOLVED_ESERIVES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYNC_CONTROL
--------------------------------------------------------

  ALTER TABLE "MYTODO"."SYNC_CONTROL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYNC_JOB
--------------------------------------------------------

  ALTER TABLE "MYTODO"."SYNC_JOB" ADD PRIMARY KEY ("SYNC_JOB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "MYTODO"."TEST" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "MYTODO"."USERS" ADD PRIMARY KEY ("LOGIN_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WWSTATISTICMAP
--------------------------------------------------------

  ALTER TABLE "MYTODO"."WWSTATISTICMAP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WWSTATISTICTOP10
--------------------------------------------------------

  ALTER TABLE "MYTODO"."WWSTATISTICTOP10" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MYTODO"  ENABLE;
