# Generated by Django 2.0 on 2018-02-12 08:37

import auth_sys.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2_provider.generators
import oauth2_provider.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=100, unique=True)),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated', validators=[oauth2_provider.validators.validate_uris])),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32)),
                ('authorization_grant_type', models.CharField(choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials')], max_length=32)),
                ('client_secret', models.CharField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('skip_authorization', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to=auth_sys.models.application_logo)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Valid for complete anonymous apps. Requires admin permission')),
                ('required_scopes', models.CharField(blank=True, help_text='Default non-tracking permissions. Valid only if application is anonymous', max_length=256, null=True)),
                ('private_scopes', models.CharField(blank=True, help_text='Private API scopes', max_length=256, null=True)),
                ('website', models.URLField()),
                ('privacy_policy', models.URLField(blank=True, help_text='Link of privacy policy of application', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_sys_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OAUTH2_PROVIDER_APPLICATION',
            },
        ),
    ]
