"""
Django settings for my_to_do project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from my_to_do.settings_dev import *


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    #     'mtksdaap23', 'mtksdaap25',
    #     '172.21.66.2', '172.21.66.13',
    "*"
]

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# use dev db for demo
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': '172.21.104.100:1521/cqp8',
        'USER': 'mytodo',
        'PASSWORD': 'mytodo',
    }
}

# fix the deploy warnnings

CSRF_COOKIE_SECURE = False
X_FRAME_OPTIONS = 'DENY'

# logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
    },
    'formatters': {
        'verbose': {
            'format': u'%(asctime)s %(levelname)s %(thread)d %(filename)s:%(lineno)d %(funcName)s %(message)s',
            'datefmt': "%Y-%m-%d %H:%M:%S"
        },
        'simple': {
            'format': u'%(asctime)s %(levelname)s %(message)s',
            'datefmt': "%Y-%m-%d %H:%M:%S"
        },
    },
    'handlers': {
        'applogfile': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(tempfile.gettempdir(), 'mytodo_ap_prod_{}.log'.format(socket.gethostname())),
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 30,  # 450 MB
            'formatter': 'verbose'
        },
        'default': {
            'formatter': 'simple',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'aplogger': {
            'handlers': ['applogfile', 'default'],
            'level': 'INFO',
        },
        'django': {
            'handlers': ['applogfile', 'default'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['applogfile', 'default'],
            'level': 'ERROR',
            'propagate': False,
        },
    }
}

CRM_CONNECTION_STRING = "mytodo/mytodomtk@172.21.104.228:1521/esvp"
ODR_CONNECTION_STRING = "mytodoreader/mytodoreader_mtk@mtkodrdbp1.mediatek.inc:1521/odrp"
SMTP_SERVER = "172.21.101.73"
